name: mrp_phone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  animated_splash_screen: ^1.3.0
  get: ^4.7.2
  firebase_database: ^11.3.4
  firebase_core: ^3.12.1  # Updated to match cloud_firestore requirement
  firebase_auth: ^5.5.1   # Updated to maintain consistency
  cloud_firestore: ^5.6.5  # Kept the same
  #shared_preferences: ^2.1.0
  shared_preferences: ^2.0.0  # Downgraded for stability
  line_awesome_flutter: ^3.0.1
  get_storage: ^2.1.1
  path_provider: ^2.1.2  # Downgraded to avoid compile errors

  flutter_launcher_icons: "^0.14.3"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Downgraded for compatibility

dependency_overrides:
  path_provider_android: 2.2.0  # Override to a stable version

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcomePage_images/welcome_screen_image.png
    - assets/logo/google_logo.png
    - assets/animations/Splash.json
    - assets/OnBoarding gifs/ONboarding1.json
    - assets/OnBoarding gifs/ONboarding2.json
    - assets/OnBoarding gifs/ONboarding3.json
    - assets/images/home/egg.png
    - assets/images/home/milk.png
    - assets/images/home/mango.png
    - assets/images/home/chicken.png
    - assets/images/home/mutton.png
    - assets/images/home/beef.png
    - assets/images/home/carrot.png
    - assets/images/home/tomato.png
    - assets/images/home/potato.png
    - assets/images/home/rice.png
    - assets/images/home/oil.png
    - assets/images/home/dal.png
    - assets/images/profile/profile.png
